#!/bin/bash
[ ${CHEF_ENV} ] || CHEF_ENV="${HNPREFIX}001.${DOMAIN}"

for NODE in $(knife node list)
do
  ping -c 1 -t 2 ${NODE} >/dev/null 2>&1
  if [ ! $? = 0 ]
  then
    echo "Unavailable: ${NODE}"
    continue
  fi
  ssh -ttq ${NODE} 'sudo /sbin/shutdown -h now'
done
