#!/bin/bash

for node in $(seq -f %04g 4 1 8)
do
  knife role run_list clear ${HNPREFIX}${node}_lab_fewt_com
  knife role run_list add ${HNPREFIX}${node}_${RLSUFFIX} "recipe[rancher::rancher_server]"
  ssh -ttq ${HNPREFIX}${node}.${DOMAIN} sudo chef-client
done
