#!/bin/bash

for node in $(seq -f %04g 4 1 8)
do
  knife node run_list remove ${HNPREFIX}${node}.${DOMAIN} "role[${HNPREFIX}${node}_${RLSUFFIX}]"
  knife node run_list add ${HNPREFIX}${node}.${DOMAIN} "provisioned_services::rebuild_self"
  ssh -ttq ${HNPREFIX}${node}.${DOMAIN} sudo chef-client
done
